language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

matrix:
  exclude:
    - if: env(skipTests) = true
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "pypy"
    - python: "pypy3"
      
cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - git clone https://github.com/smartsheet-platform/smartsheet-sdk-tests.git
  - smartsheet-sdk-tests/travis_scripts/install_wiremock.sh

install:
  - pip install --upgrade pip
  - pip install certifi
  - pip install enum34 requests six python-dateutil coverage coveralls[yaml] pytest pytest-travis-fold pytest-instafail requests-toolbelt

script:
  - smartsheet-sdk-tests/travis_scripts/start_wiremock.sh
  - coverage run --source=smartsheet setup.py test

after_success:
  - coveralls --verbose

deploy:
  provider: script
  script: sh deploy.sh
  if: env(deploy) = true

